version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "04:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
  assignees:
    - "yildiz-online"
  commit-message:
    prefix: "[UPGRADE]"
    include: "scope"
